services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/kolasokol/bladevault:latest
    container_name: bladevault
    ports:
      - "5500:3000"
    volumes:
      - ./data:/app/data
    environment:
      NODE_ENV: production
      PORT: 3000
      NEXT_PUBLIC_BLADEVAULT_AUTH_URL: ${NEXT_PUBLIC_BLADEVAULT_AUTH_URL:-}
      NEXT_PUBLIC_BLADEVAULT_BACKUP_URL: ${NEXT_PUBLIC_BLADEVAULT_BACKUP_URL:-}
